name: first actions
on: 
  push:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: echo command
       run: echo "shiva"
     - name: mutli command
       run: |
         git -v
         docker -v
