name : first github actions
on : push 

jobs : 
  name : first job
    runs-on : ubuntu-latest
     steps : 
     - name : echo a string 
       run : echo "Hello world"
     - name : multiline command
       run : |
        node -v
        docker -v 
